[DPE-6254] Update README.md
canonical/kafka-benchmark-operator pull request #2
Opened 2024-12-19 16:03 UTC by phvalguima

Updates the README with new instructions.

2024-12-20 06:22 UTC, imanenami submitted a review, later dismissed
LGTM thanks! Although I recommend getting a review from @izmalk too.

2025-01-08 16:57 UTC, marcoppenheimer approved these changes

2025-01-09 18:06 UTC, phvalguima commented on README.md
> +The benchmark data will be collected every 10s and sent to prometheus.
Added, can you check?

2025-01-09 19:22 UTC, izmalk requested changes
Good job!
Left a few suggestions to improve.
Terminology notes (`Apache Kafka`) should be considered as blocking.

2025-01-09 19:22 UTC, izmalk commented on README.md
> +Deploy the benchmark tool and relate:
**Suggestion:** Minor wording improvement and adding an empty line before the code block (recommended).

```suggestion
Deploy the benchmark tool and relate it to the cluster:

```

2025-01-09 19:22 UTC, izmalk commented on README.md
> +To stop the benchmark, execute:
```suggestion
To stop the benchmark, execute:

```

2025-01-09 19:22 UTC, izmalk commented on README.md
> +Optionally, it is possible to clean the current benchmark data using:
```suggestion
Optionally, it is possible to clean the current benchmark data using:

```

2025-01-09 19:22 UTC, izmalk commented on README.md
> +That will return all kafka-benchmark units to its original condition as well as the kafka cluster.
```suggestion
That will return both Apache Kafka benchmark charm and Apache Kafka cluster to their original condition.
```

2025-01-09 19:22 UTC, izmalk commented on README.md
> +Relate the kafka benchmark with a [`grafana-agent` operator](https://charmhub.io/grafana-agent). For more details on how to configure COS and its agents, check [the upstream documentation](https://ch
**todo:** Terminology fixes
```suggestion
Relate the Apache Kafka benchmark with a [`grafana-agent` operator](https://charmhub.io/grafana-agent). For more details on how to deploy and configure COS and its agents, check [the upstream documentation](https://charmhub.io/grafana-agent/docs/using).
```

**Question:** Is that link sufficient for deploying COS and `grafana-agent`? Wouldn't a link to the [Apache Kafka monitoring How to guide](https://canonical.com/data/docs/kafka/iaas/h-enable-monitoring) better?

2025-01-09 19:22 UTC, izmalk commented on README.md
> +Charmed Apache Kafka is free software, distributed under the Apache Software License, version 2.0. See [LICENSE](https://github.com/canonical/kafka-benchmark-operator/blob/main/LICENSE) for more info
**Suggestion:** We already have such a Licence notice for the Charmed Apache Kafka in its respective repo.
I think here we want to write about the product of this repo - Apache Kafka benchmark operator.
Alternatively, we can mention Apache Kafka benchmark charm. There is a subtle difference between them but I might not have the most precise understanding from legal perspective.

```suggestion
Apache Kafka benchmark operator is free software, distributed under the Apache Software License, version 2.0. See [LICENSE](https://github.com/canonical/kafka-benchmark-operator/blob/main/LICENSE) for more information.
```

2025-01-10 14:51 UTC, phvalguima commented on LICENSE
> +   Copyright 2024 Canonical Ltd.
Updated to 2025

2025-01-10 20:22 UTC, izmalk reviewed
One question seems to be missing an answer.

2025-01-11 15:38 UTC, phvalguima commented on README.md
> +Relate the kafka benchmark with a [`grafana-agent` operator](https://charmhub.io/grafana-agent). For more details on how to configure COS and its agents, check [the upstream documentation](https://ch
@izmalk the link to grafana-agent is correct. RE:the steps to set up COS, I am moving to the Apache Kafka guide as you've referenced.

2025-01-13 08:40 UTC, deusebio submitted a review, later dismissed
Looks good!! Thanks!

2025-01-13 21:53 UTC, deusebio approved these changes
I would remove the dismissal of approvals with new push, such that I don't have to keep on approving the PRs for minor changes. That's generally the standard in the other repos as this is kinda reducing our velocity without providing good value (as long as we are in a trusted and accountable environment)

2025-01-14 19:47 UTC, izmalk approved these changes

2025-01-15 08:10 UTC, merged